// main.js
import './style.css'

document.querySelector('#app').innerHTML = `
  <div id="game-container">
    <canvas id="canvas" oncontextmenu="event.preventDefault()" tabindex=-1></canvas>
  </div>
`

// Define the canvas for Emscripten
var Module = {
  canvas: (function() {
    var canvas = document.getElementById('canvas');
    return canvas;
  })(),
  print: (text) => console.log(text),
  printErr: (text) => console.error(text),
  setStatus: (text) => console.log("Status:", text),
  monitorRunDependencies: (left) => console.log("Downloads left:", left)
};

// Load the Emscripten glue script dynamically
const script = document.createElement('script');
script.src = "/bh.js"; // This file will be generated by the build
script.onload = () => {
    console.log("Game Loaded");
};
document.body.appendChild(script);

// Make Module global so the glue script can find it
window.Module = Module;